FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8

WORKDIR /app

# Copie le fichier requirements.txt dans le conteneur
COPY requirements.txt /app/

# Copie le répertoire app dans le conteneur
COPY ./app /app

RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "app.app:app", "--host", "0.0.0.0", "--port", "80"]


